#!/bin/bash

#########################################################
# Installation script for proto-pi device
#########################################################

# if not exists micronets group
[ $(getent group micronets) ] || sudo groupadd micronets

# Add user to required groups
sudo usermod -a -G micronets, netdev, gpio

# Add micronets to sudoers (no password for shutdown, restart lightdm, reboot, rsync)
sudo cp -f files/010_micronets /etc/sudoers.d

# Add desktop startup files
cp -f files/proto-pi.desktop ~/.config/autostart

# Build and install wpa_supplicant
!TODO

# Generate device public/private key pair
!TODO


