#!/bin/bash

# set current dir to where this script lives
pushd "${0%/*}" > /dev/null

#########################################################
# Installation script for proto-pi device
#########################################################

# sudo privileges required by proto-pi
./bin/_sudoers.sh

# Add user to required groups
echo "*** Adding user $USER to groups: netdev, gpio ***" 
sudo usermod -a -G netdev,gpio $USER

# Create desktop autostart shortcut
./bin/_desktop.sh

# Install required python modules
./bin/_pip3.sh

# Install system services (splash screens)
./bin/_services.sh

# Disable onboard wifi adapter
# (not sure why sudo is required here, sudo is present for commands in script)
sudo ./bin/_wireless.sh

# PiTFT screen configuration
./bin/_pitft.sh

# Build and install wpa_supplicant
./bin/_wpa_supplicant.sh

# Check for OS version specific settings
sudo ./bin/_version.sh

# Restart?
read -r -p "Reboot Now? [y/N] " response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]
then
	sudo reboot 
fi

popd > /dev/null

#########################################################
# Notes
#########################################################
#
# - keypair is generated on first run.
# - boilerplate config file is created on first run