#!/bin/bash

# This script is just for updating the python files remotely while developing
# Ultimately you should check in your changes and 'git pull' from the device

thisdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

pushd $thisdir > /dev/null

if [ -z $1 ]; then 
	echo "usage ./upload <host> (eg. pi@192.168.0.xx)"
else
	rsync --verbose --force --recursive ../python3 $1:~/micronets-pi3/
	date
fi
