#!/bin/bash

if [ ! -z $1 ]; then 
	echo "usage ./upload <host> (eg. micronets@192.168.0.22)"
else
	rsync --verbose --force --rsync-path="sudo rsync" --recursive ~/github/micronets/micronets-pi3/python3 $HOST:/etc/micronets/
	rsync --verbose --force --rsync-path="sudo rsync" --exclude config.json --recursive ~/github/micronets/micronets-pi3/config $HOST:/etc/micronets/
	rsync --verbose --force --rsync-path="sudo rsync" --recursive ~/github/micronets/micronets-pi3/networks $HOST:/etc/micronets/

	date
fi


# TODO: Add separate script to install systemd services, lightdm startup files, /etc/micronets file system
#rsync --verbose --force --rsync-path="sudo rsync" ~/github/micronets/micronets-pi3/install/init.d/protomed $HOST:/etc/init.d/
